language: node_js
node_js:
  - 12
script: npm start
notifications:
  slack:
    rooms:
      - campvanilla:hiyxbpbi43CtrNh8egdlWcld
    template:
      - "%{message} | %{result}"
      - "Cron Job Details: %{build_url}"
